<?php


// Default language
$language = isset($_SESSION['language']) ? $_SESSION['language'] : 'English';

// Language translations for different languages
$texts = [
    'English' => [
        'welcome' => 'Welcome to Votlink App',
        'description' => 'Empowering Ugandans with a secure and easy-to-use mobile voting system. Cast your vote with confidence in your preferred language.',
        'login' => 'Voter Login',
        'register' => 'Register as a Voter',
        'nira_id' => 'NIRA ID',
        'why_choose' => 'Why Choose Votlink App?',
        'secure' => 'Secure Voting',
        'secure_desc' => 'Your vote is confidential and secure. We use advanced encryption to protect your data.',
        'easy' => 'Easy to Use',
        'easy_desc' => 'Designed with simplicity in mind, so everyone can vote with ease.',
        'multi_language' => 'Multi-language Support',
        'multi_language_desc' => 'Vote in your preferred language: English, Luganda, Karamojong, or Kiswahili.',
        'invalid_nira' => 'Invalid NIRA ID or not registered.',
        'no_account' => "Don't have an account?",
        'register_here' => 'Register here',
        'registration_success' => 'Registration successful!',
        'registration_fail' => 'Registration failed, please try again.',
        'nira_not_found' => 'NIRA ID not found or not eligible.',
        'voter_registration' => 'Voter Registration',
        'already_registered' => 'Already registered?',
        'login_here' => 'Login here',
    ],
    'Luganda' => [
        'welcome' => 'Tusanyuse okukulaba ku Votlink App',
        'description' => 'Okuyambako Bannayuganda n’enkola y’okuvuganya eyangu era esigibwa. Fuga akalulu k’ossuubirwa nga owera omutima.',
        'login' => 'Login ya Abalonzi',
        'register' => 'Weeronde nga Omulonzi',
        'nira_id' => 'NIRA ID',
        'why_choose' => 'Lwaki okozesa Votlink App?',
        'secure' => 'Okulonda okw’ekyama',
        'secure_desc' => 'Ekalulu kammwe kiyibwa munda. Tukozesa enkola y’okutereka endagiriro okw’ekyama.',
        'easy' => 'Kyangu okukozesa',
        'easy_desc' => 'Tukola nga kyangu okukozesa, buli muntu asobola okulonda nga afunye obulungi.',
        'multi_language' => 'Obuyambi bw’ennimi',
        'multi_language_desc' => 'Londa mu lulimi lw’oyagala: Luganda, Karamojong, Kiswahili, oba Olungereza.',
        'invalid_nira' => 'NIRA ID eno tebannaba kwewandiisa.',
        'no_account' => 'Tolinga akawunta?',
        'register_here' => 'Weewandiise wano',
        'registration_success' => 'Okwandikibwa kuwedde bulungi!',
        'registration_fail' => 'Okwandikibwa kwaakulema, gezako nate.',
        'nira_not_found' => 'NIRA ID eno teriwo oba teriiko.',
        'voter_registration' => 'Okwewandiisa nga omulonzi',
        'already_registered' => 'Oweewandiisa dda?',
        'login_here' => 'Jjangu wano okweyingiza',
    ],
    'Karamojong' => [
        'welcome' => 'Iki jawunitai na Votlink App',
        'description' => 'Tusaidia wananchi wa Uganda na mfumo wa kupiga kura ulio salama na rahisi kutumia. Pigia kura kwa amani katika lugha unayoipenda.',
        'login' => 'Ingia ya Mpiga Kura',
        'register' => 'Jiandikishe kama Mpiga Kura',
        'nira_id' => 'NIRA ID',
        'why_choose' => 'Kwa nini uchague Votlink App?',
        'secure' => 'Kupiga kura kwa usalama',
        'secure_desc' => 'Kura yako ni siri na salama. Tunatumia usimbaji wa hali ya juu kulinda data yako.',
        'easy' => 'Rahisi kutumia',
        'easy_desc' => 'Imeundwa kwa urahisi ili kila mtu aweze kupiga kura kwa urahisi.',
        'multi_language' => 'Msaada wa Lugha nyingi',
        'multi_language_desc' => 'Piga kura kwa lugha unayoipenda: Luganda, Karamojong, Kiswahili, au Kiingereza.',
        'invalid_nira' => 'NIRA ID haijajisajiliwa.',
        'no_account' => 'Huna akaunti?',
        'register_here' => 'Jiandikishe hapa',
        'registration_success' => 'Usajili umekamilika!',
        'registration_fail' => 'Usajili umeshindwa, jaribu tena.',
        'nira_not_found' => 'NIRA ID haijapatikana au haifai.',
        'voter_registration' => 'Usajili wa Mpiga Kura',
        'already_registered' => 'Umesajiliwa tayari?',
        'login_here' => 'Ingia hapa',
    ],
    'Kiswahili' => [
        'welcome' => 'Karibu kwenye Votlink App',
        'description' => 'Tunawezesha wananchi wa Uganda kwa mfumo wa kupiga kura ulio salama na rahisi kutumia. Pigia kura kwa uhakika katika lugha unayoipenda.',
        'login' => 'Ingia kama Mpiga Kura',
        'register' => 'Jiandikishe kama Mpiga Kura',
        'nira_id' => 'NIRA ID',
        'why_choose' => 'Kwa nini uchague Votlink App?',
        'secure' => 'Kupiga Kura kwa Usalama',
        'secure_desc' => 'Kura yako ni siri na salama. Tunatumia usimbaji wa hali ya juu kulinda data yako.',
        'easy' => 'Rahisi Kutumia',
        'easy_desc' => 'Imeundwa kwa urahisi ili kila mtu aweze kupiga kura kwa urahisi.',
        'multi_language' => 'Msaada wa Lugha Nyingi',
        'multi_language_desc' => 'Piga kura kwa lugha unayoipenda: Luganda, Karamojong, au Kiingereza.',
        'invalid_nira' => 'NIRA ID haijasajiliwa au haiko sahihi.',
        'no_account' => 'Huna akaunti?',
        'register_here' => 'Jiandikishe hapa',
        'registration_success' => 'Usajili umefanikiwa!',
        'registration_fail' => 'Usajili umeshindwa, tafadhali jaribu tena.',
        'nira_not_found' => 'NIRA ID haikupatikana au haifai.',
        'voter_registration' => 'Usajili wa Mpiga Kura',
        'already_registered' => 'Umesajiliwa tayari?',
        'login_here' => 'Ingia hapa',
    ]
];